# docker-compose.yml
version: "3.8"
services:
   frontend:
     build:
       context: .
       dockerfile: Dockerfile
     volumes:
       - ./:/frontend:delegated
       - /node_modules
     ports:
       - 3000:3000
     environment:
       - CHOKIDAR_USEPOLLING=true
