# Use this tool to format your yml files
# https://jsonformatter.org/yaml-formatter

version: '3.8'
services:
  postgres:
    image: 'postgres:13'
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: ethan
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - transcendance_ntw
  test-postgres:
    image: 'postgres:13'
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: ethan
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - transcendance_ntw

networks:
  transcendance_ntw: null