# docker-compose.yml
version: "3.8"
services:
   frontend:
     build:
       context: .
       dockerfile: Dockerfile
     volumes:
       - ./:/react-docker:delegated
       - /node_modules
     ports:
       - 8080:8080
     environment:
       - CHOKIDAR_USEPOLLING=true
